---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull chinmayrk9/mini:v1

    - name: running container
      shell: docker create -it --name Calc chinmayrk9/mini:v1
